import { useEffect, useState } from 'react'
import AdminPageHeader from '../../components/admin/AdminPageHeader'
import Button from '../../components/common/Button'
import Input from '../../components/common/Input'
import { adminApi } from '../../services/admin/adminApi'
import { showErrorToast, showSuccessToast } from '../../utils/toast'

const Settings = () => {
  const [settings, setSettings] = useState({ storeName: 'Zivaro Fashion', contactEmail: 'amandhulkar0079@gmail.com', contactPhone: '8952004922', address: 'Jaipur, Rajasthan', shippingCharges: 99, expressShippingCharges: 199, freeShippingLimit: 2999, gstPercentage: 18, currency: 'INR', socialLinks: {}, policies: {} })
  const [saving, setSaving] = useState(false)

  useEffect(() => { adminApi.getSettings().then(({ data }) => data && setSettings((current)=>({ ...current, ...data, socialLinks: data.socialLinks || {}, policies: data.policies || {} }))) }, [])

  const update = (field, value) => setSettings((current)=>({ ...current, [field]: value }))
  const updateNested = (group, field, value) => setSettings((current)=>({ ...current, [group]: { ...current[group], [field]: value } }))
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const { data } = await adminApi.updateSettings(settings); setSettings((current)=>({ ...current, ...data })); showSuccessToast('Settings saved') } catch (error) { showErrorToast(error.response?.data?.message || 'Settings save failed') } finally { setSaving(false) } }

  return <section><AdminPageHeader eyebrow="Configuration" title="Store Settings" subtitle="Manage business details, shipping, GST, currency and policies." /><form onSubmit={submit} className="space-y-6"><div className="luxury-card grid gap-5 p-6 md:grid-cols-2"><Input label="Store Name" value={settings.storeName || ''} onChange={(e)=>update('storeName', e.target.value)} /><Input label="Currency" value={settings.currency || ''} onChange={(e)=>update('currency', e.target.value)} /><Input label="Contact Email" value={settings.contactEmail || ''} onChange={(e)=>update('contactEmail', e.target.value)} /><Input label="Contact Phone" value={settings.contactPhone || ''} onChange={(e)=>update('contactPhone', e.target.value)} /><Input className="md:col-span-2" label="Address" value={settings.address || ''} onChange={(e)=>update('address', e.target.value)} /></div><div className="luxury-card grid gap-5 p-6 md:grid-cols-4"><Input label="Shipping Charges" type="number" value={settings.shippingCharges || 0} onChange={(e)=>update('shippingCharges', Number(e.target.value))} /><Input label="Express Shipping" type="number" value={settings.expressShippingCharges || 0} onChange={(e)=>update('expressShippingCharges', Number(e.target.value))} /><Input label="Free Shipping Limit" type="number" value={settings.freeShippingLimit || 0} onChange={(e)=>update('freeShippingLimit', Number(e.target.value))} /><Input label="GST %" type="number" value={settings.gstPercentage || 0} onChange={(e)=>update('gstPercentage', Number(e.target.value))} /></div><div className="luxury-card grid gap-5 p-6 md:grid-cols-2"><Input label="Instagram" value={settings.socialLinks?.instagram || ''} onChange={(e)=>updateNested('socialLinks', 'instagram', e.target.value)} /><Input label="Facebook" value={settings.socialLinks?.facebook || ''} onChange={(e)=>updateNested('socialLinks', 'facebook', e.target.value)} /><Input label="YouTube" value={settings.socialLinks?.youtube || ''} onChange={(e)=>updateNested('socialLinks', 'youtube', e.target.value)} /><Input label="Pinterest" value={settings.socialLinks?.pinterest || ''} onChange={(e)=>updateNested('socialLinks', 'pinterest', e.target.value)} /></div><div className="luxury-card grid gap-5 p-6"><Input as="textarea" label="Return Policy" value={settings.policies?.returnPolicy || ''} onChange={(e)=>updateNested('policies', 'returnPolicy', e.target.value)} /><Input as="textarea" label="Privacy Policy" value={settings.policies?.privacyPolicy || ''} onChange={(e)=>updateNested('policies', 'privacyPolicy', e.target.value)} /><Input as="textarea" label="Terms & Conditions" value={settings.policies?.termsConditions || ''} onChange={(e)=>updateNested('policies', 'termsConditions', e.target.value)} /><Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save Settings'}</Button></div></form></section>
}
export default Settings
