import { FiFacebook, FiInstagram, FiMail, FiMapPin, FiPhone } from 'react-icons/fi'
import { Link } from 'react-router-dom'
import Button from '../common/Button'
import Container from '../common/Container'
import Input from '../common/Input'
import { showSuccessToast } from '../../utils/toast'
import { footerLinks } from '../../constants/siteData'
const Footer = () => <footer className="bg-primary text-secondary"><Container className="grid gap-10 py-14 lg:grid-cols-[1.4fr_2fr_1.2fr]"><div><h2 className="text-2xl font-extrabold uppercase tracking-[0.24em]">Zivaro <span className="text-accent">Fashion</span></h2><p className="mt-5 text-sm leading-7 text-white/70">Premium women’s fashion for modern wardrobes — curated dresses, tailoring, eveningwear and accessories with a polished luxury feel.</p><div className="mt-6 flex gap-4 text-xl"><a href="https://instagram.com" aria-label="Instagram"><FiInstagram /></a><a href="https://facebook.com" aria-label="Facebook"><FiFacebook /></a></div></div><div className="grid gap-8 sm:grid-cols-3">{Object.entries(footerLinks).map(([group, links])=><div key={group}><h3 className="text-xs font-semibold uppercase tracking-[0.22em] text-white/80">{group}</h3><div className="mt-5 grid gap-3 text-sm text-white/65">{links.map((l)=><Link key={l.label} to={l.path} onClick={()=>window.scrollTo({ top: 0, behavior: 'smooth' })} className="hover:text-accent">{l.label}</Link>)}</div></div>)}</div><div><h3 className="text-xs font-semibold uppercase tracking-[0.22em] text-white/80">Newsletter</h3><p className="mt-5 text-sm leading-7 text-white/70">Private previews, new edits and styling notes.</p><div className="mt-5 space-y-3"><Input placeholder="Email address" inputClassName="border-white/20 bg-white/10 text-secondary placeholder:text-white/50" /><Button className="w-full" onClick={()=>showSuccessToast('You are on the Zivaro list.')}>Subscribe</Button></div><div className="mt-6 space-y-2 text-sm text-white/65"><p className="flex gap-2"><FiMail /> amandhulkar0079@gmail.com</p><p className="flex gap-2"><FiPhone /> +91 89520 04922</p><p className="flex gap-2"><FiMapPin /> Jaipur, Rajasthan</p></div></div></Container><div className="border-t border-white/10 py-5 text-center text-xs uppercase tracking-[0.22em] text-white/50">© 2026 Zivaro Fashion. All rights reserved.</div></footer>
export default Footer
