import { FiMinus, FiPlus, FiShoppingBag, FiTrash2 } from 'react-icons/fi'
import Button from '../../components/common/Button'
import Container from '../../components/common/Container'
import EmptyState from '../../components/common/EmptyState'
import PageHeader from '../../components/common/PageHeader'
import { formatPrice } from '../../data/products'
import { useCart } from '../../hooks/useCart'
const Cart = () => { const { cartItems, removeFromCart, updateQuantity, clearCart, subtotal, savings, deliveryCharge, grandTotal } = useCart(); return <><PageHeader eyebrow="Shopping bag" title="Your cart" subtitle="Cart is fully functional locally with persistent quantities and totals." breadcrumbs={[{label:'Home',to:'/'},{label:'Cart'}]} /><section className="section-y"><Container>{cartItems.length ? <div className="grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-4">{cartItems.map(item=><div key={item.key} className="luxury-card grid gap-4 p-4 md:grid-cols-[130px_1fr_auto]"><div className={`aspect-square rounded-2xl bg-gradient-to-br ${item.imageTone}`} /><div><p className="caption">{item.category}</p><h3 className="mt-2 text-xl font-semibold">{item.name}</h3><p className="mt-2 small-text">Size: {item.size} · Color: {item.color}</p><p className="mt-3 font-semibold">{formatPrice(item.price)}</p></div><div className="flex items-center gap-3 md:flex-col md:items-end"><div className="flex items-center gap-2"><button className="rounded-full border p-2" onClick={()=>updateQuantity(item.key,item.quantity-1)}><FiMinus /></button><span className="w-8 text-center">{item.quantity}</span><button className="rounded-full border p-2" onClick={()=>updateQuantity(item.key,item.quantity+1)}><FiPlus /></button></div><button onClick={()=>removeFromCart(item.key)} className="text-danger"><FiTrash2 /></button><p className="font-semibold">{formatPrice(item.price * item.quantity)}</p></div></div>)}</div><aside className="luxury-card h-fit p-6"><h2 className="text-xl font-semibold">Order Summary</h2><div className="mt-6 space-y-3 small-text"><p className="flex justify-between"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></p><p className="flex justify-between text-success"><span>Savings</span><span>-{formatPrice(savings)}</span></p><p className="flex justify-between"><span>Delivery</span><span>{deliveryCharge ? formatPrice(deliveryCharge) : 'Free'}</span></p><div className="rounded-2xl border border-dashed border-line p-4">Coupon placeholder</div><p className="flex justify-between border-t border-line pt-4 text-lg font-semibold text-text"><span>Grand Total</span><span>{formatPrice(grandTotal)}</span></p></div><Button to="/checkout" className="mt-6 w-full">Proceed to Checkout</Button><Button variant="outline" className="mt-3 w-full" onClick={clearCart}>Clear Cart</Button></aside></div> : <EmptyState icon={FiShoppingBag} title="Your bag is empty" message="Add products from the shop to see local cart totals and quantity controls." />}</Container></section></> }
export default Cart
